---
- name: add fish path
  lineinfile:
    path: /etc/shells
    line: '/usr/local/bin/fish'
  become: yes
- name: use fish as default shell
  command: chsh -s /usr/local/bin/fish
- name: make the fisherman directory
  file:
    path: ~/.config/fish/functions
    state: directory
    mode: 0755
    recurse: yes
- name: install fisher
  get_url:
    url: https://git.io/fisher
    dest: ~/.config/fish/functions/fisher.fish
- name: add plugins
  command: /usr/local/bin/fish -c 'fisher add {{ item }}'
  with_items:
    - 0rax/fish-bd
    - daenney/rbenv
    - evanlucas/fish-kubectl-completions
    - jethrokuan/fzf
    - jethrokuan/z
    - oh-my-fish/plugin-osx
    - oh-my-fish/plugin-wifi-password
    - simnalamburt/shellder
- name: add docker completions
  get_url:
    url: https://raw.githubusercontent.com/docker/cli/master/contrib/completion/fish/docker.fish
    dest: ~/.config/fish/completions/docker.fish
