---
- name: install mac store applications
  command: mas install {{ item.id }}
  with_items:
    - name: Keynote
      id: 409183694
    - name: LINE
      id: 539883307
    - name: Tweetbot
      id: 557168941
