---
- name: tap homebrew repositories
  homebrew_tap:
    name: homebrew/services
    state: present

- name: install brew packages
  homebrew:
    state: installed
    name:
      - ansible
      - bat
      - bitrise
      - cocoapods
      - dart
      - fish
      - fzf
      - git
      - github/gh/gh
      - heroku/brew/heroku
      - jq
      - mas
      - postgresql
      - rbenv
      - ruby-build
      - tree
      - yarn

- name: install brew cask packages
  homebrew_cask:
    state: installed
    name:
      - 1password
      - appcleaner
      - arctype
      - caffeine
      - cinch
      - cloudflare-warp
      - discord
      - docker
      - dropbox
      - figma
      - firefox
      - fliqlo
      - flutter
      - flux
      - google-chrome
      - imageoptim
      - insomnia
      - iterm2
      - kindle
      - notion
      - numi
      - skitch
      - slack
      - the-unarchiver
      - tradingview
      - tweetbot
      - visual-studio-code
      - vlc
