---
- name: tap homebrew repositories
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/services

- name: update homebrew
  homebrew: update_homebrew=yes upgrade_all=yes

- name: install brew packages
  homebrew: name={{ item }} state=latest
  with_items:
    - ansible
    - git
    - heroku
    - argon/mas/mas
    - mysql
    - rbenv
    - rmtrash
    - ruby-build
    - tree
    # - postgresql
    # - pyenv

- name: install brew cask packages
  homebrew_cask: name={{ item }} state=installed
  with_items:
    - 1password
    - appcleaner
    - atom
    - caffeine
    - day-o
    - dropbox
    - fliqlo
    - flux
    - google-chrome
    - iterm2
    - sequel-pro
    - slack
    - vivaldi
    - vlc
    # - android-studio
    # - cyberduck
    # - docker
    # - evernote
    # - firefox
    # - java
    # - realm-browser
    # - skitch
    # - skype
    # - vagrant
    # - virtualbox

- name: start mysql at login
  shell: brew services start mysql
  # shell: brew services start postgresql
