---
- name: tap homebrew repositories
  homebrew_tap:
    name: homebrew/services
    state: present

- name: install brew packages
  homebrew:
    name: "{{ item }}"
    state: installed
  with_items:
    - ansible
    - fish
    - fzf
    - git
    - heroku/brew/heroku
    - hub
    - jq
    - mas
    - mysql-client
    - rbenv
    - rmtrash
    - ruby-build
    - tree
    - yarn

- name: install brew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: installed
  with_items:
    - 1password
    - appcleaner
    - caffeine
    - cinch
    - dash
    - day-o
    - docker
    - dropbox
    - figma
    - fliqlo
    - flux
    - google-chrome
    - google-photos-backup-and-sync
    - homebrew/cask-fonts/font-source-code-pro
    - homebrew/cask-versions/firefox-developer-edition
    - imageoptim
    - insomnia
    - iterm2
    - kindle
    - sequel-pro
    - skitch
    - skype
    - slack
    - spotify
    - the-unarchiver
    - trailer
    - visual-studio-code
    - vlc
