- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_taps:
      - caskroom/cask
    homebrew_packages:
      - { name: git }
      - { name: mysql }
      - { name: rbenv }
      - { name: ruby-build }
    homebrew_cask_packages:
      - { name: 1password }
      - { name: appcleaner }
      - { name: atom }
      - { name: caffeine }
      - { name: dash }
      - { name: dropbox }
      - { name: evernote }
      - { name: flux }
      - { name: google-chrome }
      - { name: hub }
      - { name: iterm2 }
      - { name: mailbox }
      - { name: sequel-pro }
      - { name: skitch }
      - { name: skype }
      - { name: slack }
      - { name: vagrant }
      - { name: virtualbox }

  tasks:
    - name: tap homebrew repositories
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: update homebrew
      homebrew: update_homebrew=yes upgrade_all=yes

    - name: install brew packages
      homebrew: name={{ item.name }} state={{ item.state | default('latest') }} install_options={{ item.install_options | default() }}
      with_items: homebrew_packages

    - name: install homebrew-cask
      homebrew: name=brew-cask state=latest

    - name: install brew cask packages
      homebrew_cask: name={{ item.name }} state={{ item.state | default('installed') }}
      with_items: homebrew_cask_packages

    - name: copy .bash_aliases
      copy: src=./files/.bash_aliases dest=~/.bash_aliases
      register: dot_bash_aliases

    - name: copy .bash_exports
      copy: src=./files/.bash_exports dest=~/.bash_exports
      register: dot_bash_exports

    - name: copy .bash_profile
      copy: src=./files/.bash_profile dest=~/.bash_profile
      register: dot_bash_profile

    - name: copy .bash_prompt
      copy: src=./files/.bash_prompt dest=~/.bash_prompt
      register: dot_bash_prompt

    - name: copy .gitconfig
      copy: src=./files/.gitconfig dest=~/.gitconfig
      register: dot_gitconfig

    - name: copy .inputrc
      copy: src=./files/.inputrc dest=~/.inputrc
      register: dot_inputrc

    - name: load dotfile settings
      shell: source ~/.bash_profile
      when: dot_bash_aliases.changed or dot_bash_exports.changed or dot_bash_profile.changed or dot_bash_prompt.changed or dot_gitconfig.changed or dot_inputrc.changed
