- name: Create a 4096-bit SSH key
  user:
    name: tetsuya
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
- name: Evaluate the authentication agent & adding the key
  shell: |
    eval "$(ssh-agent)"
    ssh-add ~/.ssh/id_rsa

- name: Check ruby installation
  shell: rbenv versions | grep {{ ruby_version }}
  register: ruby_installed
  ignore_errors: yes

- name: Install {{ ruby_version }}
  shell: rbenv install {{ ruby_version }}
  when: ruby_installed is failed

- name: Set ruby {{ ruby_version }} as system
  shell: rbenv global {{ ruby_version }}
  when: ruby_installed is failed

- name: Save settings
  shell: rbenv rehash
  when: ruby_installed is failed

- name: Set gh alias
  shell: gh alias set open 'repo view -w'
