- name: Create a 4096-bit SSH key
  user:
    name: tetsuya
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
- name: Evaluate the authentication agent & adding the key
  shell: |
    eval "$(ssh-agent)"
    ssh-add ~/.ssh/id_rsa