---
- name: Set computer name (as done via System Preferences -> Sharing)
  become: sudo
  command: "{{ item }}"
  with_items:
    - scutil --set ComputerName "mbp"
    - scutil --set HostName "mbp"
    - scutil --set LocalHostName "mbp"

- name: Autohide Dock
  shell: defaults write com.apple.dock autohide -bool true && killall Dock

- name: Disable the drop-shadow on screenshots
  shell: defaults write com.apple.screencapture disable-shadow -bool true && killall SystemUIServer
